/** Generated by scripts/seo/measure-current-product-media.ts. */
export type CurrentProductMediaMeasurement = {
  byteSize: number | null;
  height: number | null;
  mimeType: string | null;
  width: number | null;
};

export const CURRENT_PRODUCT_MEDIA_MEASUREMENTS: Readonly<Record<string, CurrentProductMediaMeasurement>> = {
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782805470813-screenshot-2026-06-15-193206.png": {
    "byteSize": 588326,
    "height": 538,
    "mimeType": "image/png",
    "width": 1105
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782805473415-screenshot-2026-06-15-193218.png": {
    "byteSize": 453125,
    "height": 531,
    "mimeType": "image/png",
    "width": 984
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782805475761-chatgpt-image-jun-30-2026-12-55-15-pm.png": {
    "byteSize": 2292400,
    "height": 1672,
    "mimeType": "image/png",
    "width": 941
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782806174622-screenshot-2026-06-15-204603.png": {
    "byteSize": 554180,
    "height": 523,
    "mimeType": "image/png",
    "width": 1081
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782806177265-chatgpt-image-jun-30-2026-01-21-57-pm.png": {
    "byteSize": 1955310,
    "height": 1672,
    "mimeType": "image/png",
    "width": 941
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782806180159-chatgpt-image-jun-30-2026-01-25-48-pm.png": {
    "byteSize": 1930830,
    "height": 1672,
    "mimeType": "image/png",
    "width": 941
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782807347365-chatgpt-image-jun-30-2026-01-38-35-pm.png": {
    "byteSize": 2086475,
    "height": 1672,
    "mimeType": "image/png",
    "width": 941
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782807351327-screenshot-2026-06-15-204627.png": {
    "byteSize": 605864,
    "height": 543,
    "mimeType": "image/png",
    "width": 1057
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782807353636-screenshot-2026-06-15-204817.png": {
    "byteSize": 656877,
    "height": 639,
    "mimeType": "image/png",
    "width": 1051
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782814545765-chatgpt-image-jun-30-2026-02-29-13-pm.png": {
    "byteSize": 2506739,
    "height": 1672,
    "mimeType": "image/png",
    "width": 941
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782814551149-chatgpt-image-jun-30-2026-02-29-04-pm.png": {
    "byteSize": 2333950,
    "height": 1672,
    "mimeType": "image/png",
    "width": 941
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782814554143-chatgpt-image-jun-30-2026-01-13-21-pm.png": {
    "byteSize": 2277764,
    "height": 1672,
    "mimeType": "image/png",
    "width": 941
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782818994553-chatgpt-image-jun-30-2026-04-54-28-pm-1.png": {
    "byteSize": 2310381,
    "height": 1672,
    "mimeType": "image/png",
    "width": 941
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782818997672-chatgpt-image-jun-30-2026-04-54-28-pm-2.png": {
    "byteSize": 2077104,
    "height": 1672,
    "mimeType": "image/png",
    "width": 941
  },
  "https://ll1rv51y3jxrt1nr.public.blob.vercel-storage.com/media/1782819027130-image-2-edited.jpg": {
    "byteSize": 274522,
    "height": 1500,
    "mimeType": "image/jpeg",
    "width": 1200
  },
  "https://mgkwfyatucnr0yzo.public.blob.vercel-storage.com/media/1775564943332-img-2125.jpg": {
    "byteSize": 9763908,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://mgkwfyatucnr0yzo.public.blob.vercel-storage.com/media/1775564965605-img-2129.jpg": {
    "byteSize": 8899767,
    "height": 2714,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://mgkwfyatucnr0yzo.public.blob.vercel-storage.com/media/1775564972291-img-2138.jpg": {
    "byteSize": 9866734,
    "height": 2713,
    "mimeType": "image/jpeg",
    "width": 5182
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775402255525-img-1351.jpg": {
    "byteSize": 10653332,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775402262238-img-1352.jpg": {
    "byteSize": 10751433,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775402269330-img-1354.jpg": {
    "byteSize": 8136670,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775402277654-img-1355.jpg": {
    "byteSize": 8369207,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775402285754-img-1358.jpg": {
    "byteSize": 10648497,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775402293218-img-1360.jpg": {
    "byteSize": 9275619,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775402300042-img-1362.jpg": {
    "byteSize": 13580231,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775402307946-img-1364.jpg": {
    "byteSize": 9359502,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775402313924-img-1367.jpg": {
    "byteSize": 8152795,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775402321730-img-1368.jpg": {
    "byteSize": 11023161,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775402328352-img-1369.jpg": {
    "byteSize": 11602417,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775403313754-img-1429.jpg": {
    "byteSize": 10617959,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775403321107-img-1430.jpg": {
    "byteSize": 7824617,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775403328643-img-1431.jpg": {
    "byteSize": 8893473,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775403335125-img-1437.jpg": {
    "byteSize": 8260043,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775403341916-img-1444.jpg": {
    "byteSize": 8630222,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775403350745-img-1446.jpg": {
    "byteSize": 9318913,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775403359106-img-1447.jpg": {
    "byteSize": 10562366,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775403366194-img-1451.jpg": {
    "byteSize": 8683316,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775403371975-img-1453.jpg": {
    "byteSize": 9635485,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775403381414-img-1454.jpg": {
    "byteSize": 9229754,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404071689-img-1703.jpg": {
    "byteSize": 11906207,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404080856-img-1717.jpg": {
    "byteSize": 16669954,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404089993-img-1721.jpg": {
    "byteSize": 16774702,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404099585-img-1725.jpg": {
    "byteSize": 11688957,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404106904-img-1730.jpg": {
    "byteSize": 6994143,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404114589-img-1731.jpg": {
    "byteSize": 12684674,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404122871-img-1733.jpg": {
    "byteSize": 7219531,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404129731-img-1736.jpg": {
    "byteSize": 7921780,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404136458-img-1739.jpg": {
    "byteSize": 7337296,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404144956-img-1740.jpg": {
    "byteSize": 8695263,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404404968-img-1747-edit.jpg": {
    "byteSize": 9490955,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404411978-img-1790-edit.jpg": {
    "byteSize": 10846727,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404418596-img-1793-edit.jpg": {
    "byteSize": 11494005,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404428479-img-1796-edit.jpg": {
    "byteSize": 12367352,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404435820-img-1803-edit.jpg": {
    "byteSize": 10163318,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404442372-img-1804-edit-2.jpg": {
    "byteSize": 7005962,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404448661-img-1805-edit.jpg": {
    "byteSize": 8790216,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404456476-img-1810-edit.jpg": {
    "byteSize": 9424744,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775404463362-img-1814-edit.jpg": {
    "byteSize": 13532959,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775461171537-img-1658.jpg": {
    "byteSize": 3816983,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775622396373-img-2091.jpg": {
    "byteSize": 7480190,
    "height": 3077,
    "mimeType": "image/jpeg",
    "width": 4616
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775622403733-img-2110.jpg": {
    "byteSize": 5045042,
    "height": 3692,
    "mimeType": "image/jpeg",
    "width": 2459
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775622435611-img-2112.jpg": {
    "byteSize": 7196462,
    "height": 3871,
    "mimeType": "image/jpeg",
    "width": 2579
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775622443310-img-2111.jpg": {
    "byteSize": 4812629,
    "height": 4059,
    "mimeType": "image/jpeg",
    "width": 2124
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775660537196-img-7328.jpg": {
    "byteSize": 13039783,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775660700230-img-7324.jpg": {
    "byteSize": 7617354,
    "height": 4148,
    "mimeType": "image/jpeg",
    "width": 2765
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775660711766-img-7335.jpg": {
    "byteSize": 13277255,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775660724044-img-7334.jpg": {
    "byteSize": 12059841,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775660733051-img-7329.jpg": {
    "byteSize": 10139367,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775660744998-img-7336.jpg": {
    "byteSize": 5018138,
    "height": 3419,
    "mimeType": "image/jpeg",
    "width": 2279
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775660753236-img-7328.jpg": {
    "byteSize": 13039783,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775661207233-img-1645-edit.jpg": {
    "byteSize": 7748115,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775661217215-img-1658.jpg": {
    "byteSize": 6875542,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775661224586-img-1660.jpg": {
    "byteSize": 9960918,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775661232440-img-1678.jpg": {
    "byteSize": 8219824,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775661240041-img-1685.jpg": {
    "byteSize": 8481214,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775661248945-img-1656.jpg": {
    "byteSize": 9294889,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775663367854-img-2169.jpg": {
    "byteSize": 2128792,
    "height": 1358,
    "mimeType": "image/jpeg",
    "width": 2038
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775663525608-img-2161.jpg": {
    "byteSize": 5278199,
    "height": 3672,
    "mimeType": "image/jpeg",
    "width": 2448
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775663551192-img-2159.jpg": {
    "byteSize": 4141519,
    "height": 3498,
    "mimeType": "image/jpeg",
    "width": 2331
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775665094387-img-2163.jpg": {
    "byteSize": 4204865,
    "height": 3654,
    "mimeType": "image/jpeg",
    "width": 2435
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775665102616-img-2171.jpg": {
    "byteSize": 10130363,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775665111822-img-2174.jpg": {
    "byteSize": 5642961,
    "height": 3400,
    "mimeType": "image/jpeg",
    "width": 2266
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775665120162-img-2156.jpg": {
    "byteSize": 1677750,
    "height": 1279,
    "mimeType": "image/jpeg",
    "width": 1920
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775665126121-img-2159.jpg": {
    "byteSize": 4141519,
    "height": 3498,
    "mimeType": "image/jpeg",
    "width": 2331
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775665133473-img-2165.jpg": {
    "byteSize": 12533053,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775665142926-img-2168.jpg": {
    "byteSize": 13581638,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775665153077-img-2173.jpg": {
    "byteSize": 6008057,
    "height": 3493,
    "mimeType": "image/jpeg",
    "width": 2328
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775665160783-img-2169.jpg": {
    "byteSize": 2128792,
    "height": 1358,
    "mimeType": "image/jpeg",
    "width": 2038
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775665168128-img-2164.jpg": {
    "byteSize": 2295814,
    "height": 2513,
    "mimeType": "image/jpeg",
    "width": 1674
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775665173933-img-2170.jpg": {
    "byteSize": 13365597,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775665183671-img-2161.jpg": {
    "byteSize": 5278199,
    "height": 3672,
    "mimeType": "image/jpeg",
    "width": 2448
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775665191122-img-2158.jpg": {
    "byteSize": 5150895,
    "height": 2782,
    "mimeType": "image/jpeg",
    "width": 4174
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753011312-img-6410.jpg": {
    "byteSize": 11346110,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753020244-img-6403.jpg": {
    "byteSize": 4307807,
    "height": 3269,
    "mimeType": "image/jpeg",
    "width": 1712
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753027256-dsc09272.jpg": {
    "byteSize": 40018987,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753047610-img-6400.jpg": {
    "byteSize": 5047769,
    "height": 3746,
    "mimeType": "image/jpeg",
    "width": 1961
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753057737-dsc09243.jpg": {
    "byteSize": 12391041,
    "height": 5000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753066604-c0010t01.jpg": {
    "byteSize": 997214,
    "height": 1280,
    "mimeType": "image/jpeg",
    "width": 720
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753072646-img-6398.jpg": {
    "byteSize": 4483342,
    "height": 2839,
    "mimeType": "image/jpeg",
    "width": 1892
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753079568-img-6406.jpg": {
    "byteSize": 3450070,
    "height": 3595,
    "mimeType": "image/jpeg",
    "width": 2396
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753085656-c0009t01.jpg": {
    "byteSize": 482985,
    "height": 720,
    "mimeType": "image/jpeg",
    "width": 1280
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753091183-dsc09240.jpg": {
    "byteSize": 14823373,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753101274-dsc09277.jpg": {
    "byteSize": 43104094,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753126535-img-6409.jpg": {
    "byteSize": 7070931,
    "height": 4777,
    "mimeType": "image/jpeg",
    "width": 2501
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753136605-img-6404.jpg": {
    "byteSize": 8544424,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775753147104-img-6411.jpg": {
    "byteSize": 10450641,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805403360-dsc09282.jpg": {
    "byteSize": 27774254,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805417577-dsc09292.jpg": {
    "byteSize": 26552325,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805464388-img-6421.jpg": {
    "byteSize": 11801899,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805472050-dsc09258.jpg": {
    "byteSize": 40720403,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805509348-img-6418.jpg": {
    "byteSize": 15559861,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805519964-dsc09298.jpg": {
    "byteSize": 25676252,
    "height": 5487,
    "mimeType": "image/jpeg",
    "width": 3657
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805534176-dsc09284.jpg": {
    "byteSize": 28178689,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805548388-img-6416.jpg": {
    "byteSize": 14378496,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805558350-img-6422.jpg": {
    "byteSize": 7926958,
    "height": 4067,
    "mimeType": "image/jpeg",
    "width": 2711
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805566742-dsc09269.jpg": {
    "byteSize": 38604162,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805583198-img-6413.jpg": {
    "byteSize": 6996687,
    "height": 2641,
    "mimeType": "image/jpeg",
    "width": 3962
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805590671-img-6417.jpg": {
    "byteSize": 7101080,
    "height": 3863,
    "mimeType": "image/jpeg",
    "width": 2575
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805598109-img-6420.jpg": {
    "byteSize": 7909644,
    "height": 4061,
    "mimeType": "image/jpeg",
    "width": 2707
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805608355-img-6414.jpg": {
    "byteSize": 8094388,
    "height": 4814,
    "mimeType": "image/jpeg",
    "width": 3209
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775805615523-dsc09313.jpg": {
    "byteSize": 14055431,
    "height": 4286,
    "mimeType": "image/jpeg",
    "width": 2857
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775833070169-dsc09223.jpg": {
    "byteSize": 13681180,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775833094866-dsc09236.jpg": {
    "byteSize": 33099657,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775833124090-dsc09237.jpg": {
    "byteSize": 15498849,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775833137576-dsc09210.jpg": {
    "byteSize": 12713747,
    "height": 4557,
    "mimeType": "image/jpeg",
    "width": 3037
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775833145857-dsc09214.jpg": {
    "byteSize": 17131848,
    "height": 5721,
    "mimeType": "image/jpeg",
    "width": 3813
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775833158151-dsc09239.jpg": {
    "byteSize": 23795332,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775833171501-c0007t01.jpg": {
    "byteSize": 835463,
    "height": 1280,
    "mimeType": "image/jpeg",
    "width": 720
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775833178013-dsc09230.jpg": {
    "byteSize": 20114945,
    "height": 5422,
    "mimeType": "image/jpeg",
    "width": 3614
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775833190861-dsc09222.jpg": {
    "byteSize": 15438633,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775833202480-dsc09219.jpg": {
    "byteSize": 17316601,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775833214884-dsc09226.jpg": {
    "byteSize": 16395341,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775896526791-img-7451.jpg": {
    "byteSize": 15618193,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775896535620-img-7450.jpg": {
    "byteSize": 15439928,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775896544301-img-7447.jpg": {
    "byteSize": 10185452,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775896552705-img-7449.jpg": {
    "byteSize": 13662299,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775896562173-img-7446.jpg": {
    "byteSize": 13032375,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1775973570941-img-2204.jpg": {
    "byteSize": 8932954,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776078862669-img-2193.jpg": {
    "byteSize": 4331105,
    "height": 2288,
    "mimeType": "image/jpeg",
    "width": 3433
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776078889611-img-2200.jpg": {
    "byteSize": 10187084,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776078901550-img-2202.jpg": {
    "byteSize": 4688604,
    "height": 3469,
    "mimeType": "image/jpeg",
    "width": 2312
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776078907552-img-2198.jpg": {
    "byteSize": 9994509,
    "height": 4783,
    "mimeType": "image/jpeg",
    "width": 3188
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776078915848-img-2207.jpg": {
    "byteSize": 6349552,
    "height": 2737,
    "mimeType": "image/jpeg",
    "width": 4106
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776078922125-img-2199.jpg": {
    "byteSize": 9990505,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776078938889-img-2201.jpg": {
    "byteSize": 6486428,
    "height": 4058,
    "mimeType": "image/jpeg",
    "width": 2702
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776078946225-img-2203.jpg": {
    "byteSize": 9144217,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776078974805-img-2195.jpg": {
    "byteSize": 4422658,
    "height": 3444,
    "mimeType": "image/jpeg",
    "width": 2296
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776078980248-img-2206.jpg": {
    "byteSize": 8337519,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776078987544-img-2211.jpg": {
    "byteSize": 11121444,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776078995292-img-2214.jpg": {
    "byteSize": 4551458,
    "height": 3526,
    "mimeType": "image/jpeg",
    "width": 2350
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776079000219-img-2208.jpg": {
    "byteSize": 5633940,
    "height": 3882,
    "mimeType": "image/jpeg",
    "width": 2587
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776308348251-img-7236.jpg": {
    "byteSize": 11371356,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776308358721-img-7233.jpg": {
    "byteSize": 10628518,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776308368781-img-7231.jpg": {
    "byteSize": 8151441,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776308377585-img-7239.jpg": {
    "byteSize": 9705942,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776308385516-img-7237.jpg": {
    "byteSize": 11813734,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776308396480-img-7232.jpg": {
    "byteSize": 1813238,
    "height": 2188,
    "mimeType": "image/jpeg",
    "width": 1459
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776308404244-img-7238.jpg": {
    "byteSize": 11742149,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776308415521-img-7235.jpg": {
    "byteSize": 8731738,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776583599077-img-7369.jpg": {
    "byteSize": 10935459,
    "height": 4166,
    "mimeType": "image/jpeg",
    "width": 2777
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776583611692-img-7378.jpg": {
    "byteSize": 4202667,
    "height": 1811,
    "mimeType": "image/jpeg",
    "width": 2716
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776583620003-img-7383.jpg": {
    "byteSize": 14220377,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776583637881-img-7381.jpg": {
    "byteSize": 15932235,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776583651605-img-7382.jpg": {
    "byteSize": 7539083,
    "height": 3468,
    "mimeType": "image/jpeg",
    "width": 2312
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776583670085-img-7379.jpg": {
    "byteSize": 2654780,
    "height": 2033,
    "mimeType": "image/jpeg",
    "width": 1355
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776583678290-img-7380.jpg": {
    "byteSize": 14250206,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776583690446-img-7370.jpg": {
    "byteSize": 8313825,
    "height": 3273,
    "mimeType": "image/jpeg",
    "width": 2182
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776583705663-img-7372.jpg": {
    "byteSize": 3091051,
    "height": 2233,
    "mimeType": "image/jpeg",
    "width": 1489
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776600071387-img-6523.jpg": {
    "byteSize": 14336066,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776600091085-img-6513.jpg": {
    "byteSize": 7891381,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776600102379-img-6516.jpg": {
    "byteSize": 10438370,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776600119754-img-6524.jpg": {
    "byteSize": 9215943,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776600130833-img-6526.jpg": {
    "byteSize": 16735327,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776680761820-img-7017.jpg": {
    "byteSize": 13740438,
    "height": 7542,
    "mimeType": "image/jpeg",
    "width": 5028
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776680770327-img-7018.jpg": {
    "byteSize": 14714077,
    "height": 7110,
    "mimeType": "image/jpeg",
    "width": 4740
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776680777896-img-7019.jpg": {
    "byteSize": 14027427,
    "height": 6899,
    "mimeType": "image/jpeg",
    "width": 4599
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776680785244-img-7020.jpg": {
    "byteSize": 23520316,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776776510942-dsc00069-2.jpg": {
    "byteSize": 2960874,
    "height": 2685,
    "mimeType": "image/jpeg",
    "width": 1790
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776776529767-dsc00072-2.jpg": {
    "byteSize": 4778483,
    "height": 3516,
    "mimeType": "image/jpeg",
    "width": 2344
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776776535936-dsc00070-2.jpg": {
    "byteSize": 3596279,
    "height": 3022,
    "mimeType": "image/jpeg",
    "width": 2015
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776777760397-img-1939-2.jpg": {
    "byteSize": 5929707,
    "height": 4882,
    "mimeType": "image/jpeg",
    "width": 2559
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776777794309-img-1899-2.jpg": {
    "byteSize": 9931578,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776777801580-img-1925-2.jpg": {
    "byteSize": 9232840,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776777809198-img-1920-2.jpg": {
    "byteSize": 8211774,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3084
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776777815343-img-1924-2.jpg": {
    "byteSize": 10129987,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776777822816-img-1918-2.jpg": {
    "byteSize": 9403447,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776777829518-img-1926-2.jpg": {
    "byteSize": 9205150,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776777836529-img-1905-2.jpg": {
    "byteSize": 10772396,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776777954480-dsc09195-2.jpg": {
    "byteSize": 7685436,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776777981922-dsc09200-2.jpg": {
    "byteSize": 5251114,
    "height": 4171,
    "mimeType": "image/jpeg",
    "width": 2780
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776777987888-img-2190-2.jpg": {
    "byteSize": 8016923,
    "height": 4963,
    "mimeType": "image/jpeg",
    "width": 3308
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776777994343-dsc09186-2.jpg": {
    "byteSize": 9203084,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778000484-dsc09188-2.jpg": {
    "byteSize": 7799622,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778006417-img-2187-2.jpg": {
    "byteSize": 4237343,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778153599-img-6429-2.jpg": {
    "byteSize": 4105445,
    "height": 4356,
    "mimeType": "image/jpeg",
    "width": 2904
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778174460-img-6434-2.jpg": {
    "byteSize": 11218872,
    "height": 6912,
    "mimeType": "image/jpeg",
    "width": 7930
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778202220-img-6425-2.jpg": {
    "byteSize": 5652486,
    "height": 4120,
    "mimeType": "image/jpeg",
    "width": 2747
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778208071-img-6430-2.jpg": {
    "byteSize": 2948246,
    "height": 3640,
    "mimeType": "image/jpeg",
    "width": 2427
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778327583-dsc09052-2.jpg": {
    "byteSize": 14404469,
    "height": 10789,
    "mimeType": "image/jpeg",
    "width": 7464
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778356924-c0046t01-2.jpg": {
    "byteSize": 712918,
    "height": 1280,
    "mimeType": "image/jpeg",
    "width": 720
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778360958-dsc09043-2.jpg": {
    "byteSize": 16498821,
    "height": 12000,
    "mimeType": "image/jpeg",
    "width": 8000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778370263-c0053t01-2.jpg": {
    "byteSize": 492742,
    "height": 1280,
    "mimeType": "image/jpeg",
    "width": 720
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778373740-c0042t01-2.jpg": {
    "byteSize": 396598,
    "height": 1280,
    "mimeType": "image/jpeg",
    "width": 720
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778377548-c0047t01-2.jpg": {
    "byteSize": 714884,
    "height": 1280,
    "mimeType": "image/jpeg",
    "width": 720
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778644037-dsc09122-2.jpg": {
    "byteSize": 19167860,
    "height": 12000,
    "mimeType": "image/jpeg",
    "width": 8000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778674094-dsc09113-2.jpg": {
    "byteSize": 16942325,
    "height": 12000,
    "mimeType": "image/jpeg",
    "width": 8000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778699761-dsc09162-2.jpg": {
    "byteSize": 19877384,
    "height": 8087,
    "mimeType": "image/jpeg",
    "width": 8000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778835599-dsc09116-2.jpg": {
    "byteSize": 17698037,
    "height": 12000,
    "mimeType": "image/jpeg",
    "width": 8000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778846204-dsc09114-2.jpg": {
    "byteSize": 14103812,
    "height": 10568,
    "mimeType": "image/jpeg",
    "width": 8000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776778853711-dsc09119-2.jpg": {
    "byteSize": 16417789,
    "height": 12000,
    "mimeType": "image/jpeg",
    "width": 8000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776779793039-dsc09354-2.jpg": {
    "byteSize": 13370119,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776779822551-dsc09340-2.jpg": {
    "byteSize": 19030167,
    "height": 12000,
    "mimeType": "image/jpeg",
    "width": 8000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776779835632-dsc09332-2.jpg": {
    "byteSize": 20196522,
    "height": 12000,
    "mimeType": "image/jpeg",
    "width": 8000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776779844848-c0036t01-2.jpg": {
    "byteSize": 1099424,
    "height": 2560,
    "mimeType": "image/jpeg",
    "width": 1440
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776779848551-dsc09363-2.jpg": {
    "byteSize": 17871388,
    "height": 12000,
    "mimeType": "image/jpeg",
    "width": 8000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776780003751-img-1516-2.jpg": {
    "byteSize": 11973066,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776780023489-img-1530-2.jpg": {
    "byteSize": 11742100,
    "height": 9462,
    "mimeType": "image/jpeg",
    "width": 5875
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776780034184-img-1524-2.jpg": {
    "byteSize": 9380968,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776780040947-img-1573-2.jpg": {
    "byteSize": 11432903,
    "height": 8572,
    "mimeType": "image/jpeg",
    "width": 5270
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776780049549-img-1548-2.jpg": {
    "byteSize": 13447296,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776780057441-img-1537-2.jpg": {
    "byteSize": 13664037,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776780569488-img-7408-3.jpg": {
    "byteSize": 12004866,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776780600153-img-7405-3.jpg": {
    "byteSize": 15881642,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776780607974-img-7406-3.jpg": {
    "byteSize": 15178735,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776780622591-dsc00133-2.jpg": {
    "byteSize": 6471092,
    "height": 7872,
    "mimeType": "image/jpeg",
    "width": 5248
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776780628224-img-6862-3.jpg": {
    "byteSize": 8708553,
    "height": 6912,
    "mimeType": "image/jpeg",
    "width": 10368
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776781073377-img-7153-2.jpg": {
    "byteSize": 11292115,
    "height": 6813,
    "mimeType": "image/jpeg",
    "width": 6812
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776781090716-img-7151-2.jpg": {
    "byteSize": 23679284,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776781113481-img-7148-2.jpg": {
    "byteSize": 15802855,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776781123153-img-7142-2.jpg": {
    "byteSize": 19718377,
    "height": 10106,
    "mimeType": "image/jpeg",
    "width": 6737
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776781131123-img-7139-2.jpg": {
    "byteSize": 13004817,
    "height": 8886,
    "mimeType": "image/jpeg",
    "width": 5924
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776781139857-img-7150-2.jpg": {
    "byteSize": 19474586,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776781239271-img-7345-2.jpg": {
    "byteSize": 15759478,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776781247723-img-7344-2.jpg": {
    "byteSize": 20909612,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776781387196-img-7443-2.jpg": {
    "byteSize": 16549365,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776781420415-img-7441-2.jpg": {
    "byteSize": 22364706,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776781428382-img-7442-2.jpg": {
    "byteSize": 14303791,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776781433897-img-7438-2.jpg": {
    "byteSize": 11970235,
    "height": 8237,
    "mimeType": "image/jpeg",
    "width": 5884
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776859639555-img-7176-2.jpg": {
    "byteSize": 10716751,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776859671066-img-7177-2.jpg": {
    "byteSize": 15729032,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776859698265-img-7195-2.jpg": {
    "byteSize": 20601982,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776859724403-img-7181-2.jpg": {
    "byteSize": 13568489,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776859793015-img-7192-2.jpg": {
    "byteSize": 12617680,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776860582137-img-7165-2.jpg": {
    "byteSize": 9871373,
    "height": 8517,
    "mimeType": "image/jpeg",
    "width": 5678
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776860659613-img-7161-2.jpg": {
    "byteSize": 21712618,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776860957055-img-7174-2.jpg": {
    "byteSize": 10560458,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776860968077-img-7164-3.jpg": {
    "byteSize": 15596226,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776860980905-img-7165-2.jpg": {
    "byteSize": 9871373,
    "height": 8517,
    "mimeType": "image/jpeg",
    "width": 5678
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776860995714-img-7168-2.jpg": {
    "byteSize": 14192224,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776861296387-img-7215-2.jpg": {
    "byteSize": 12564542,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776861313525-img-7198-2.jpg": {
    "byteSize": 12324728,
    "height": 8640,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776861335001-img-7203-2.jpg": {
    "byteSize": 13708595,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776861366167-img-7211-2.jpg": {
    "byteSize": 23570804,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776861377677-img-7213-2.jpg": {
    "byteSize": 18710169,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776861409099-img-7201-2.jpg": {
    "byteSize": 10540668,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776862182112-img-6456-2.jpg": {
    "byteSize": 11600976,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 5867
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776862192090-img-6458-2.jpg": {
    "byteSize": 12127198,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776862201175-img-6466-2.jpg": {
    "byteSize": 16949209,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776862209483-img-6460-2.jpg": {
    "byteSize": 13771408,
    "height": 10368,
    "mimeType": "image/jpeg",
    "width": 6912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776870590822-img-7410.jpg": {
    "byteSize": 9822307,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776870619202-img-7421.jpg": {
    "byteSize": 10179780,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776870665404-img-7413.jpg": {
    "byteSize": 6242647,
    "height": 4320,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776870672110-img-7416.jpg": {
    "byteSize": 10762182,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776870679399-img-7417.jpg": {
    "byteSize": 10017481,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776870905835-img-7360.jpg": {
    "byteSize": 9994178,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776870927846-img-7349.jpg": {
    "byteSize": 7492801,
    "height": 4771,
    "mimeType": "image/jpeg",
    "width": 3180
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776870947794-img-7364.jpg": {
    "byteSize": 10004246,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776870966647-img-7353.jpg": {
    "byteSize": 7196482,
    "height": 4400,
    "mimeType": "image/jpeg",
    "width": 3299
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776870972987-img-7355.jpg": {
    "byteSize": 10148894,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776871134578-img-7427.jpg": {
    "byteSize": 9652495,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776871165382-img-7432.jpg": {
    "byteSize": 8615669,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776871188599-img-7426.jpg": {
    "byteSize": 9405543,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776871324414-img-0001.jpeg": {
    "byteSize": 8181911,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776933816491-img-1834.jpg": {
    "byteSize": 6197435,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776933824993-img-1850-2.jpg": {
    "byteSize": 7805100,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776933831346-img-1837.jpg": {
    "byteSize": 5740605,
    "height": 4266,
    "mimeType": "image/jpeg",
    "width": 2844
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776933837283-img-1873-2.jpg": {
    "byteSize": 7516438,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776933845656-img-1894.jpg": {
    "byteSize": 4591968,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776933850118-img-1884-2.jpg": {
    "byteSize": 9316302,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776934258040-img-1975.jpg": {
    "byteSize": 9787019,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776934284843-img-1944.jpg": {
    "byteSize": 2966696,
    "height": 3177,
    "mimeType": "image/jpeg",
    "width": 2118
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776934291260-img-1946.jpg": {
    "byteSize": 8110075,
    "height": 4497,
    "mimeType": "image/jpeg",
    "width": 2998
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776934296608-img-1941.jpg": {
    "byteSize": 7136192,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776934301981-img-1943.jpg": {
    "byteSize": 4919248,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776934307948-img-1981.jpg": {
    "byteSize": 4150127,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776934311494-img-1989.jpg": {
    "byteSize": 6598320,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776938527154-img-7278.jpg": {
    "byteSize": 6969712,
    "height": 4159,
    "mimeType": "image/jpeg",
    "width": 3326
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776938555556-img-7279.jpg": {
    "byteSize": 7653796,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776938584419-img-7281.jpg": {
    "byteSize": 8411923,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776938597125-img-7288.jpg": {
    "byteSize": 8238281,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776938615390-img-7298.jpg": {
    "byteSize": 8440498,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776938679320-img-7292.jpg": {
    "byteSize": 5062655,
    "height": 4176,
    "mimeType": "image/jpeg",
    "width": 2783
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776939158515-img-1609.jpg": {
    "byteSize": 7099642,
    "height": 4850,
    "mimeType": "image/jpeg",
    "width": 3232
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776939176027-img-1588.jpg": {
    "byteSize": 10752761,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776939203214-img-1620.jpg": {
    "byteSize": 7161319,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776939210077-img-1606.jpg": {
    "byteSize": 7816243,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776939215811-img-1628.jpg": {
    "byteSize": 6621278,
    "height": 5048,
    "mimeType": "image/jpeg",
    "width": 3365
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776939223389-img-1585.jpg": {
    "byteSize": 8712160,
    "height": 4608,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776939788221-img-1467.jpg": {
    "byteSize": 5964555,
    "height": 4800,
    "mimeType": "image/jpeg",
    "width": 3199
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776939808192-img-1462.jpg": {
    "byteSize": 7245544,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776939825752-img-1465.jpg": {
    "byteSize": 6345976,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776939843597-img-1472.jpg": {
    "byteSize": 7482922,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776947385340-img-7318.jpg": {
    "byteSize": 6193037,
    "height": 4826,
    "mimeType": "image/jpeg",
    "width": 3217
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776947396439-img-7308.jpg": {
    "byteSize": 8385073,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776947408608-img-7322.jpg": {
    "byteSize": 7923953,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776947423997-img-7305.jpg": {
    "byteSize": 7004655,
    "height": 4608,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776947439915-img-7312.jpg": {
    "byteSize": 9626064,
    "height": 4964,
    "mimeType": "image/jpeg",
    "width": 3309
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776947766849-img-1763.jpg": {
    "byteSize": 8468403,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776947783718-img-1754.jpg": {
    "byteSize": 7641253,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776947798587-img-1762.jpg": {
    "byteSize": 8923450,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776947801916-img-1753.jpg": {
    "byteSize": 8689030,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776947817560-img-1779.jpg": {
    "byteSize": 8633321,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776947824635-img-1770.jpg": {
    "byteSize": 3621560,
    "height": 3811,
    "mimeType": "image/jpeg",
    "width": 2540
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776948128636-img-6496.jpg": {
    "byteSize": 11511390,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776948181942-img-6504.jpg": {
    "byteSize": 11261367,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776948189500-img-6505.jpg": {
    "byteSize": 10945102,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776948291109-img-6510-2.jpg": {
    "byteSize": 10640753,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776949026912-img-6647-2.jpg": {
    "byteSize": 9607025,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776949050853-img-6657-2.jpg": {
    "byteSize": 8055185,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776949058800-img-6662-2.jpg": {
    "byteSize": 6820704,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776949076846-img-6665-2.jpg": {
    "byteSize": 8156134,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3455
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776949520533-2.jpg": {
    "byteSize": 4607198,
    "height": 3110,
    "mimeType": "image/jpeg",
    "width": 3110
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776949527744-img-7134.jpg": {
    "byteSize": 6836048,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776949602380-img-7122.jpg": {
    "byteSize": 8397411,
    "height": 4999,
    "mimeType": "image/jpeg",
    "width": 3333
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776949607986-img-7131.jpg": {
    "byteSize": 6929991,
    "height": 4320,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776950172030-img-1396.jpg": {
    "byteSize": 9706104,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776950210420-img-1400.jpg": {
    "byteSize": 8166972,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776951045608-img-2149.jpg": {
    "byteSize": 1156669,
    "height": 1067,
    "mimeType": "image/jpeg",
    "width": 1601
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776951061704-img-2148.jpg": {
    "byteSize": 9526622,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776951065940-img-2141.jpg": {
    "byteSize": 10747393,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1776951070815-img-2143.jpg": {
    "byteSize": 8495553,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777026332729-img-1391-edit.jpg": {
    "byteSize": 6867409,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777026343853-img-1395-edit.jpg": {
    "byteSize": 4515512,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777026355214-img-1408-edit.jpg": {
    "byteSize": 6027422,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 2714
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777026364322-img-1403-edit.jpg": {
    "byteSize": 6284041,
    "height": 3456,
    "mimeType": "image/jpeg",
    "width": 5184
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777026375453-img-1404-edit.jpg": {
    "byteSize": 10840263,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777027742233-dsc09390.jpg": {
    "byteSize": 8192045,
    "height": 5236,
    "mimeType": "image/jpeg",
    "width": 3491
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777027792400-dsc09396.jpg": {
    "byteSize": 10702561,
    "height": 6000,
    "mimeType": "image/jpeg",
    "width": 4000
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777027797138-c0039t01.jpg": {
    "byteSize": 728327,
    "height": 1280,
    "mimeType": "image/jpeg",
    "width": 720
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777028329488-img-6447.jpg": {
    "byteSize": 7050297,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777028408260-img-6442.jpg": {
    "byteSize": 3886704,
    "height": 3435,
    "mimeType": "image/jpeg",
    "width": 2290
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777028427915-img-6445.jpg": {
    "byteSize": 8385592,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777028455238-img-6452.jpg": {
    "byteSize": 5568610,
    "height": 4312,
    "mimeType": "image/jpeg",
    "width": 2874
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777028469672-img-6453.jpg": {
    "byteSize": 7369104,
    "height": 5050,
    "mimeType": "image/jpeg",
    "width": 3367
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777030509883-img-6485.jpg": {
    "byteSize": 8129628,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777030584373-img-6479.jpg": {
    "byteSize": 4203476,
    "height": 3805,
    "mimeType": "image/jpeg",
    "width": 2536
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777030640003-img-6483.jpg": {
    "byteSize": 8581932,
    "height": 5184,
    "mimeType": "image/jpeg",
    "width": 3456
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777030696166-img-6489.jpg": {
    "byteSize": 5114236,
    "height": 4104,
    "mimeType": "image/jpeg",
    "width": 2735
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777030711024-img-6480.jpg": {
    "byteSize": 5254107,
    "height": 4370,
    "mimeType": "image/jpeg",
    "width": 2912
  },
  "https://njufw8f4mlcjsl7g.public.blob.vercel-storage.com/media/1777146227388-dsc00117.jpg": {
    "byteSize": 9766065,
    "height": 7872,
    "mimeType": "image/jpeg",
    "width": 5248
  }
};

export const getCurrentProductMediaMeasurement = (url: string) =>
  CURRENT_PRODUCT_MEDIA_MEASUREMENTS[url];
